name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - name: Run lint check
        run: pnpm run lint

  autofix:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - name: Fix lint issues
        run: pnpm run lint:fix
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: apply automated fixes"
          branch: ${{ github.ref }}

  merge:
    needs: [test, autofix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure branch is up to date
        run: |
          git fetch origin
          git checkout ${{ github.ref }}
          git merge origin/main
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
