name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - name: Check for eslint-config-unjs workaround
        run: |
          # Check if eslint-config-unjs needs a workaround
          if [ -d "node_modules/eslint-config-unjs" ]; then
            echo 'Adding exports field to eslint-config-unjs package.json'
            jq '. + {exports: "./index.js"}' node_modules/eslint-config-unjs/package.json > temp.json && mv temp.json node_modules/eslint-config-unjs/package.json
          fi
      - name: Fix lint issues
        run: pnpm run lint:fix
      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
        with:
          commit-message: "chore: apply automated fixes"

